#!/usr/bin/env bash
# Configure your Nginx server for redirection
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chmod 777 /usr/share/nginx/html/index.html
echo "Hello World" > /usr/share/nginx/html/index.html
sudo sed -i "38i\ \tlocation /redirect_me {\n\t\treturn 301;\n\t}\n" /etc/nginx/sites-enabled/default
sudo service nginx restart
