#!/usr/bin/env bash
# Script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line
count=1
while [[ "$count" -le 10 ]]; do
echo "Best School"
count=$((count + 1))
if [[ "$count" == 10 ]]; then
echo "Hi"
fi
done
