#!/usr/bin/env bash
# Write a Bash script that loops from 1 to 10
count=0
while [[ "$count" -le 9 ]]; do
count=$((count + 1))
if [[ "$count" == 4 ]]; then
echo "bad luck"
elif [[ "$count" == 8 ]]; then
echo "good luck"
else 
echo "Best School"
fi
done
