#!/usr/bin/env bash
# Write a Bash script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59

count=0
while [[ "$count" -le 12 ]]; do
echo "Hour: $count"
mcount=1
while [[ "$mcount" -le 59 ]]; do
echo "$mcount"
mcount=$((mcount + 1))
done
count=$((count + 1))
done
