#!/usr/bin/env bash
# Script that gives you information about the school file

FILE="school"
if [ -e "$FILE" ]
then
echo "$FILE file exists"
else
echo "$FILE file does not exist"
fi
if [ ! -s "$FILE" ]
then
 echo "$FILE file is empty"
else
echo "$FILE file is not empty"	
fi
if [ -f "$FILE" ]
then
echo "$FILE is a regular file"
else
echo ""
fi
