#!/usr/bin/env bash
# Script that gives you information about the school file

FILE="school"

if [ -e "$FILE" ]; then
 echo "$FILE file exists"
if [ ! -s "$FILE" ]; then
 echo "$FILE file is empty"
else 
 echo "$FILE is not empty"	
fi
if [ -f "$FILE" ]; then
 echo "$FILE is a regular file"
fi
else
 echo "$FILE does not exist"
fi
