#!/usr/bin/env bash
# Script that gives you information about the school file

FILE="school"
if [ -e "$FILE" ]; then
 echo "school file exists"
if [ ! -s "$FILE" ]; then
 echo "school file is empty"
else 
 echo "school is not empty"	
fi
if [ -f "$FILE" ]; then
 echo "school is a regular file"
fi
else
 echo "school does not exist"
fi
