#!/usr/bin/env bash
# Double the number of webservers
SRC="/etc/nginx/sites-available/default"
REDIR="\\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
ERRDIR="\\\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}\n"
HEADER="\\\n\tadd_header X-Served-By \$HOSTNAME;\n"
sudo apt -y update
sudo apt -y install nginx
sudo service nginx start
sudo chmod 777 /etc/nginx/sites-available/
sudo chmod 777 /etc/nginx/sites-available/default
echo "Hello World" | sudo tee /var/www/html/index.html
sudo sed -i "30i $REDIR" $SRC
sudo sed -i "28i $HEADER" $SRC
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo sed -i "48i $ERRDIR" $SRC
sudo service nginx restart
